language: php

php:
  - 5.6
  - 5.5
  - 5.4

# cache composer downloads so installing is quicker
cache:
  directories:
    - $HOME/.composer

addons:
  code_climate:
    repo_token: 9deb249b01a414d979959cfd05a4c351b19a5959858653b20276454d4189edc3

before_script:
  - sh tools/travis/setup-mail.sh
  - cp phinx.yml.dist phinx.yml
  - composer self-update
  - composer install

script:
  - sh tools/travis/build.sh

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
