application:
  title: TechCampMemphisCFP
  url: http://localhost
  email: joe@memphistechnology.org
  eventurl: http://localhost
  enddate: Oct. 14th, 2025
  show_submission_count: false
  airport: MEM
  arrival: 2025-10-26
  departure: 2025-10-31
  secure_ssl: no

api:
  enabled: true

cache:
  enabled: false

database:
  host: 127.0.0.1
  database: opencfp
  dsn: mysql:dbname=opencfp;host=127.0.0.1
  user: homestead
  password: secret

mail:
  host: ~
  port: ~
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~
